package com.evopayments.turnkey.apiclient.code;

/**
 * ISO-4217 Currency codes
 */
public enum CurrencyCode {
    ADP("ADP"), // Andorran Peseta (ANDORRA)
    AED("AED"), // UAE Dirham (UNITED ARAB EMIRATES)
    AFA("AFA"), // Afghani ( AFGHANISTAN)
    AFN("AFN"), // Afghani (AFGHANISTAN)
    ALK("ALK"), // Old Lek (ALBANIA)
    ALL("ALL"), // Lek (ALBANIA)
    AMD("AMD"), // Armenian Dram (ARMENIA)
    ANG("ANG"), // Netherlands Antillean Guilder (CURAÇAO, SINT MAARTEN (DUTCH PART), NETHERLANDS ANTILLES)
    AOA("AOA"), // Kwanza (ANGOLA)
    AOK("AOK"), // Kwanza (ANGOLA)
    AON("AON"), // New Kwanza (ANGOLA)
    AOR("AOR"), // Kwanza Reajustado (ANGOLA)
    ARA("ARA"), // Austral (ARGENTINA)
    ARP("ARP"), // Peso Argentino (ARGENTINA)
    ARS("ARS"), // Argentine Peso (ARGENTINA)
    ARY("ARY"), // Peso (ARGENTINA)
    ATS("ATS"), // Schilling (AUSTRIA)
    AUD("AUD"), // Australian Dollar (AUSTRALIA, CHRISTMAS ISLAND ,COCOS (KEELING) ISLANDS, HEARD ISLAND AND McDONALD ISLANDS, KIRIBATI, NAURU, NORFOLK ISLAND, TUVALU)
    AWG("AWG"), // Aruban Florin (ARUBA)
    AYM("AYM"), // Azerbaijan Manat (AZERBAIJAN)
    AZM("AZM"), // Azerbaijanian Manat (AZERBAIJAN)
    AZN("AZN"), // Azerbaijanian Manat (AZERBAIJAN)
    BAD("BAD"), // Dinar (BOSNIA AND HERZEGOVINA)
    BAM("BAM"), // Convertible Mark (BOSNIA AND HERZEGOVINA)
    BBD("BBD"), // Barbados Dollar (BARBADOS)
    BDT("BDT"), // Taka (BANGLADESH)
    BEC("BEC"), // Convertible Franc (BELGIUM)
    BEF("BEF"), // Belgian Franc (BELGIUM)
    BEL("BEL"), // Financial Franc (BELGIUM)
    BGJ("BGJ"), // Lev A/52 (BULGARIA)
    BGK("BGK"), // Lev A/62 (BULGARIA)
    BGL("BGL"), // Lev (BULGARIA)
    BGN("BGN"), // Bulgarian Lev (BULGARIA)
    BHD("BHD"), // Bahraini Dinar (BAHRAIN)
    BIF("BIF"), // Burundi Franc (BURUNDI)
    BMD("BMD"), // Bermudian Dollar (BERMUDA)
    BND("BND"), // Brunei Dollar (BRUNEI DARUSSALAM)
    BOB("BOB"), // Boliviano (PLURINATIONAL STATE OF BOLIVIA)
    BOP("BOP"), // Peso boliviano (BOLIVIA)
    BOV("BOV"), // Mvdol (PLURINATIONAL STATE OF BOLIVIA)
    BRB("BRB"), // Cruzeiro (BRAZIL)
    BRC("BRC"), // Cruzado (BRAZIL)
    BRE("BRE"), // Cruzeiro (BRAZIL)
    BRL("BRL"), // Brazilian Real (BRAZIL)
    BRN("BRN"), // New Cruzado (BRAZIL)
    BRR("BRR"), // Cruzeiro Real (BRAZIL)
    BSD("BSD"), // Bahamian Dollar (BAHAMAS)
    BTN("BTN"), // Ngultrum (BHUTAN)
    BUK("BUK"), // N.A. (BURMA)
    BWP("BWP"), // Pula (BOTSWANA)
    BYB("BYB"), // Belarussian Ruble (BELARUS)
    BYR("BYR"), // Belarussian Ruble (BELARUS)
    BZD("BZD"), // Belize Dollar (BELIZE)
    CAD("CAD"), // Canadian Dollar (CANADA)
    CDF("CDF"), // Congolese Franc (DEMOCRATIC REPUBLIC OF THE CONGO)
    CHC("CHC"), // WIR Franc (for electronic) (SWITZERLAND)
    CHE("CHE"), // WIR Euro (SWITZERLAND)
    CHF("CHF"), // Swiss Franc (LIECHTENSTEIN)
    CHW("CHW"), // WIR Franc (SWITZERLAND)
    CLF("CLF"), // Unidad de Fomento (CHILE)
    CLP("CLP"), // Chilean Peso (CHILE)
    CNX("CNX"), // Peoples Bank Dollar (CHINA)
    CNY("CNY"), // Yuan Renminbi (CHINA)
    COP("COP"), // Colombian Peso (COLOMBIA)
    COU("COU"), // Unidad de Valor Real (COLOMBIA)
    CRC("CRC"), // Costa Rican Colon (COSTA RICA)
    CUC("CUC"), // Peso Convertible (CUBA)
    CUP("CUP"), // Cuban Peso (CUBA)
    CVE("CVE"), // Cape Verde Escudo (CAPE VERDE)
    CYP("CYP"), // Cyprus Pound (CYPRUS)
    CZK("CZK"), // Czech Koruna (CZECH REPUBLIC)
    CSD("CSD"), // Serbian Dinar (SERBIA AND MONTENEGRO)
    CSJ("CSJ"), // Krona A/53 (CZECHOSLOVAKIA)
    CSK("CSK"), // Koruna (CZECHOSLOVAKIA)
    DDM("DDM"), // Mark der DDR (GERMAN DEMOCRATIC REPUBLIC)
    DEM("DEM"), // Deutsche Mark (GERMANY)
    DJF("DJF"), // Djibouti Franc (DJIBOUTI)
    DKK("DKK"), // Danish Krone (DENMARK, FAROE ISLANDS, GREENLAN)
    DOP("DOP"), // Dominican Peso (DOMINICAN REPUBLIC)
    DZD("DZD"), // Algerian Dinar (ALGERIA)
    ECV("ECV"), // Unidad de Valor Constante (UVC) (ECUADOR)
    ECS("ECS"), // Sucre (ECUADOR)
    EEK("EEK"), // Kroon (ESTONIA)
    EGP("EGP"), // Egyptian Pound (EGYPT)
    EQE("EQE"), // Ekwele (EQUATORIAL GUINEA)
    ERN("ERN"), // Nakfa (ERITREA)
    ESA("ESA"), // Spanish Peseta (SPAIN)
    ESB("ESB"), // "A Account (convertible Peseta Account) (SPAIN)
    ESP("ESP"), // Spanish Peseta (SPAIN, ANDORRA)
    ETB("ETB"), // Ethiopian Birr (ETHIOPIA)
    EUR("EUR"), // Euro (EUROPEAN UNION, ÅLAND ISLAND, ANDORRA, AUSTRIA, BELGIUM, CYPRUS, ESTONIA, FINLAND, FRANCE, FRENCH GUIANA, FRENCH SOUTHERN TERRITORIES, GERMANY, GREECE, GUADELOUPE, HOLY SEE (VATICAN CITY STATE), IRELAND, ITALY, LATVIA, LUXEMBOURG, MALTA, MARTINIQUE, MAYOTTE, NETHERLANDS, MONTENEGRO, MONACO, PORTUGAL, RÉUNION, SAINT BARTHÉLEMY, SAINT MARTIN (FRENCH PART), SAINT PIERRE AND MIQUELON, SAN MARINO, SLOVAKIA, SLOVENIA, SPAIN, SERBIA AND MONTENEGRO)
    FIM("FIM"), // Markka (FINLAND, ÅLAND ISLANDS)
    FJD("FJD"), // Fiji Dollar (FIJI)
    FKP("FKP"), // Falkland Islands Pound (FALKLAND ISLANDS (MALVINAS))
    FRF("FRF"), // French Franc (FRANCE, ANDORRA, FRENCH  GUIANA, FRENCH SOUTHERN TERRITORIES, GUADELOUPE, MARTINIQUE, MAYOTTE, MONACO, RÉUNION, SAINT MARTIN, SAINT PIERRE AND MIQUELON, SAINT-BARTHÉLEMY)
    GBP("GBP"), // Pound Sterling (UNITED KINGDOM, GUERNSEY, ISLE OF MAN, JERSEY)
    GEK("GEK"), // Georgian Coupon (GEORGIA)
    GEL("GEL"), // Lari (GEORGIA)
    GHC("GHC"), // Cedi (GHANA)
    GHP("GHP"), // Ghana Cedi (GHANA)
    GHS("GHS"), // Ghana Cedi (GHANA)
    GIP("GIP"), // Gibraltar Pound (GIBRALTAR)
    GMD("GMD"), // Dalasi (GAMBIA)
    GNE("GNE"), // Syli (GUINEA)
    GNF("GNF"), // Guinea Franc (GUINEA)
    GNS("GNS"), // Syli (GUINEA)
    GQE("GQE"), // Ekwele (EQUATORIAL GUINEA)
    GRD("GRD"), // Drachma (GREECE)
    GTQ("GTQ"), // Quetzal (GUATEMALA)
    GWE("GWE"), // Guinea Escudo (GUINEA-BISSAU)
    GWP("GWP"), // Guinea-Bissau Peso (GUINEA-BISSAU)
    GYD("GYD"), // Guyana Dollar (GUYANA)
    HKD("HKD"), // Hong Kong Dollar (HONG KONG)
    HNL("HNL"), // Lempira (HONDURAS)
    HRD("HRD"), // Croatian Dinar (CROATIA)
    HRK("HRK"), // Croatian Kuna (CROATIA)
    HTG("HTG"), // Gourde (HAITI)
    HUF("HUF"), // Forint (HUNGARY)
    IDR("IDR"), // Rupiah (INDONESIA, TIMOR-LESTE)
    IEP("IEP"), // Irish Pound (IRELAND)
    ILP("ILP"), // Pound (ISRAEL)
    ILR("ILR"), // Old Shekel (ISRAEL)
    ILS("ILS"), // New Israeli Sheqel (ISRAEL)
    INR("INR"), // Indian Rupee (INDIA, BHUTAN)
    IQD("IQD"), // Iraqi Dinar (IRAQ)
    IRR("IRR"), // Iranian Rial (ISLAMIC REPUBLIC OF IRAN)
    ISJ("ISJ"), // Old Krona (ICELAND)
    ISK("ISK"), // Iceland Krona (ICELAND)
    ITL("ITL"), // Italian Lira (ITALY, HOLY SEE (VATICAN CITY STATE), SAN MARINO)
    JMD("JMD"), // Jamaican Dollar (JAMAICA)
    JOD("JOD"), // Jordanian Dinar (JORDAN)
    JPY("JPY"), // Yen (JAPAN)
    KES("KES"), // Kenyan Shilling (KENYA)
    KGS("KGS"), // Som (KYRGYZSTAN)
    KHR("KHR"), // Riel (CAMBODIA)
    KMF("KMF"), // Comoro Franc (COMOROS)
    KPW("KPW"), // North Korean Won (DEMOCRATIC PEOPLE’S REPUBLIC OF KOREA)
    KRW("KRW"), // Won (REPUBLIC OF KOREA)
    KWD("KWD"), // Kuwaiti Dinar (KUWAIT)
    KYD("KYD"), // Cayman Islands Dollar (CAYMAN ISLANDS)
    KZT("KZT"), // Tenge (KAZAKHSTAN)
    LAJ("LAJ"), // Kip Pot Pol (LAO)
    LAK("LAK"), // Kip (LAO PEOPLE’S DEMOCRATIC REPUBLIC)
    LBP("LBP"), // Lebanese Pound (LEBANON)
    LKR("LKR"), // Sri Lanka Rupee (SRI LANKA)
    LRD("LRD"), // Liberian Dollar (LIBERIA)
    LSL("LSL"), // Loti (LESOTHO)
    LSM("LSM"), // Maloti (LESOTHO)
    LTL("LTL"), // Lithuanian Litas (LITHUANIA)
    LTT("LTT"), // Talonas (LITHUANIA)
    LUC("LUC"), // Luxembourg Convertible Franc (LUXEMBOURG)
    LUF("LUF"), // Luxembourg Franc (LUXEMBOURG)
    LUL("LUL"), // Luxembourg Financial Franc (LUXEMBOURG)
    LVL("LVL"), // Latvian Lats (LATVIA)
    LVR("LVR"), // Latvian Ruble (LATVIA)
    LYD("LYD"), // Libyan Dinar (LIBYA)
    MAD("MAD"), // Moroccan Dirham (MOROCCO, WESTERN SAHARA)
    MAF("MAF"), // Mali Franc (MALI)
    MDL("MDL"), // Moldovan Leu (REPUBLIC OF MOLDOVA)
    MGA("MGA"), // Malagasy Ariary (MADAGASCAR)
    MGF("MGF"), // Malagasy Franc (MADAGASCAR)
    MKD("MKD"), // Denar (THE FORMER  YUGOSLAV REPUBLIC OF MACEDONIA)
    MLF("MLF"), // Mali Franc (MALI)
    MMK("MMK"), // Kyat (MYANMAR)
    MNT("MNT"), // Tugrik (MONGOLIA)
    MOP("MOP"), // Pataca (MACAO)
    MRO("MRO"), // Ouguiya (MAURITANIA)
    MTL("MTL"), // Maltese Lira (MALTA)
    MTP("MTP"), // Maltese Pound (MALTA)
    MUR("MUR"), // Mauritius Rupee (MAURITIUS)
    MVQ("MVQ"), // Maldive Rupee (MALDIVES)
    MVR("MVR"), // Rufiyaa (MALDIVES)
    MWK("MWK"), // Kwacha (MALAWI)
    MXN("MXN"), // Mexican Peso (MEXICO)
    MXP("MXP"), // Mexican Peso (MEXICO)
    MXV("MXV"), // Mexican Unidad de Inversion (UDI) (MEXICO)
    MYR("MYR"), // Malaysian Ringgit (MALAYSIA)
    MZE("MZE"), // Mozambique Escudo (MOZAMBIQUE)
    MZM("MZM"), // Mozambique Metical (MOZAMBIQUE)
    MZN("MZN"), // Mozambique Metical (MOZAMBIQUE)
    NAD("NAD"), // Namibia Dollar (NAMIBIA)
    NGN("NGN"), // Naira (NIGERIA)
    NIC("NIC"), // Cordoba (NICARAGUA)
    NIO("NIO"), // Cordoba Oro (NICARAGUA)
    NLG("NLG"), // Netherlands Guilder (NETHERLANDS)
    NOK("NOK"), // Norwegian Krone (NORWAY, BOUVET ISLAND, SVALBARD AND JAN MAYEN)
    NPR("NPR"), // Nepalese Rupee (NEPAL
    NZD("NZD"), // New Zealand Dollar (NEW ZEALAND, COOK ISLANDS, NIUE, PITCAIRN, TOKELAU)
    OMR("OMR"), // Rial Omani (OMAN)
    PAB("PAB"), // Balboa (PANAMA)
    PEH("PEH"), // Sol (PERU)
    PEI("PEI"), // Inti (PERU)
    PEN("PEN"), // Nuevo Sol (PERU))
    PES("PES"), // Sol (PERU)
    PGK("PGK"), // Kina (PAPUA NEW GUINEA)
    PHP("PHP"), // Philippine Peso (PHILIPPINES)
    PKR("PKR"), // Pakistan Rupee (PAKISTAN)
    PLN("PLN"), // Zloty (POLAND)
    PLZ("PLZ"), // Zloty (POLAND)
    PTE("PTE"), // Portuguese Escudo (PORTUGAL
    PYG("PYG"), // Guarani (PARAGUAY
    QAR("QAR"), // Qatari Rial (QATAR)
    RHD("RHD"), // Rhodesian Dollar (SOUTHERN RHODESIA)
    ROK("ROK"), // Leu A/52 (ROMANIA)
    ROL("ROL"), // Old Leu (ROMANIA)
    RON("RON"), // New Romanian Leu (ROMANIA)
    RSD("RSD"), // Serbian Dinar (SERBIA)
    RUB("RUB"), // Russian Ruble (RUSSIAN FEDERATION)
    RUR("RUR"), // Russian Ruble (RUSSIAN FEDERATION, ARMENIA, AZERBAIJAN, BELARUS, GEORGIA, KAZAKHSTAN, KYRGYZSTAN, REPUBLIC OF MOLDOVA, TAJIKISTAN, TURKMENISTAN, UZBEKISTAN)
    RWF("RWF"), // Rwanda Franc (RWANDA)
    SAR("SAR"), // Saudi Riyal (SAUDI ARABIA)
    SBD("SBD"), // Solomon Islands Dollar (SOLOMON ISLANDS)
    SCR("SCR"), // Seychelles Rupee (SEYCHELLES)
    SDD("SDD"), // Sudanese Dinar (SUDAN)
    SDG("SDG"), // Sudanese Pound (SOUTH SUDAN, SUDAN)
    SDP("SDP"), // Sudanese Pound (SUDAN)
    SEK("SEK"), // Swedish Krona (SWEDEN)
    SGD("SGD"), // Singapore Dollar (SINGAPORE)
    SHP("SHP"), // Saint Helena Pound (SAINT HELENA, ASCENSION AND  TRISTAN DA CUNHA)
    SIT("SIT"), // Tolar (SLOVENIA)
    SKK("SKK"), // Slovak Koruna (SLOVAKIA)
    SLL("SLL"), // Leone (SIERRA LEONE)
    SOS("SOS"), // Somali Shilling (SOMALIA)
    SRD("SRD"), // Surinam Dollar (SURINAME)
    SRG("SRG"), // Surinam Guilder (SURINAME)
    SSP("SSP"), // South Sudanese Pound (SOUTH SUDAN)
    STD("STD"), // Dobra (SAO TOME AND PRINCIPE)
    SUR("SUR"), // Rouble (UNION OF SOVIET SOCIALIST REPUBLICS)
    SVC("SVC"), // El Salvador Colon (EL SALVADOR)
    SYP("SYP"), // Syrian Pound (SYRIAN ARAB REPUBLIC)
    SZL("SZL"), // Lilangeni (SWAZILAND))
    THB("THB"), // Baht (THAILAND)
    TJR("TJR"), // Tajik Ruble (TAJIKISTAN)
    TJS("TJS"), // Somoni (TAJIKISTAN)
    TMM("TMM"), // Turkmenistan Manat (TURKMENISTAN)
    TMT("TMT"), // Turkmenistan New Manat (TURKMENISTAN)
    TND("TND"), // Tunisian Dinar (TUNISIA)
    TOP("TOP"), // Pa’anga (TONGA)
    TPE("TPE"), // Timor Escudo (TIMOR-LESTE)
    TRL("TRL"), // Old Turkish Lira (TURKEY)
    TRY("TRY"), // Turkish Lira (TURKEY)
    TTD("TTD"), // Trinidad and Tobago Dollar (TRINIDAD AND TOBAGO)
    TWD("TWD"), // New Taiwan Dollar (TAIWAN)
    TZS("TZS"), // Tanzanian Shilling (UNITED REPUBLIC OF TANZANIA)
    UAH("UAH"), // Hryvnia (UKRAINE)
    UAK("UAK"), // Karbovanet (UKRAINE)
    UGS("UGS"), // Uganda Shilling (UGANDA)
    UGW("UGW"), // Old Shilling (UGANDA)
    UGX("UGX"), // Uganda Shilling (UGANDA)
    USD("USD"), // US Dollar (UNITED STATES, AMERICAN SAMOA, BONAIRE, SINT EUSTATIUS AND SABA, BRITISH INDIAN OCEAN TERRITORY, ECUADOR, EL SALVADOR, GUAM, HAITI, MARSHALL ISLANDS, FEDERATED STATES OF MICRONESIA, NORTHERN MARIANA ISLANDS, PALAU, PANAMA, PUERTO RICO, TIMOR-LESTE, TURKS AND CAICOS ISLANDS, VIRGIN ISLANDS (BRITISH) ,UNITED STATES MINOR OUTLYING ISLANDS, VIRGIN ISLANDS (U.S.))
    USN("USN"), // US Dollar (Next day) (UNITED STATES)
    USS("USS"), // US Dollar (Same day) (UNITED STATES)
    UYI("UYI"), // Uruguay Peso en Unidades Indexadas (URUIURUI) (URUGUAY)
    UYN("UYN"), // Old Uruguay Peso (URUGUAY)
    UYP("UYP"), // Uruguayan Peso (URUGUAY)
    UYU("UYU"), // Peso Uruguayo (URUGUAY)
    UZS("UZS"), // Uzbekistan Sum (UZBEKISTAN)
    VEB("VEB"), // Bolivar (VENEZUELA)
    VEF("VEF"), // Bolivar Fuerte (VENEZUELA)
    VNC("VNC"), // Old Dong (VIETNAM)
    VND("VND"), // Dong (VIETNAM)
    VUV("VUV"), // Vatu (VANUATU)
    WST("WST"), // Tala (SAMOA)
    XAF("XAF"), // CFA Franc BEAC (CAMEROON, CENTRAL AFRICAN REPUBLIC, CHAD, CONGO, EQUATORIAL GUINEA, GABON)
    XAG("XAG"), // Silver (ZZ11_Silver)
    XAU("XAU"), // Gold (ZZ08_Gold)
    XBA("XBA"), // Bond Markets Unit European Composite Unit (EURCO) (ZZ01_Bond Markets Unit European_EURCO)
    XBB("XBB"), // Bond Markets Unit European Monetary Unit (E.M.U.-6) (ZZ02_Bond Markets Unit European_EMU-6)
    XBC("XBC"), // Bond Markets Unit European Unit of Account 9 (E.U.A.-9) (ZZ03_Bond Markets Unit European_EUA-9)
    XBD("XBD"), // Bond Markets Unit European Unit of Account 17 (E.U.A.-17) (ZZ04_Bond Markets Unit European_EUA-17)
    XCD("XCD"), // East Caribbean Dollar (ANGUILLA, ANTIGUA AND BARBUDA, DOMINICA, GRENADA, MONTSERRAT, SAINT KITTS AND NEVIS, SAINT LUCIA, SAINT VINCENT AND THE GRENADINES)
    XDR("XDR"), // SDR (Special Drawing Right) (INTERNATIONAL MONETARY FUND (IMF))
    XEU("XEU"), // European Currency Unit (E.C.U) (EUROPEAN MONETARY CO-OPERATION FUND (EMCF))
    XFO("XFO"), // Gold-Franc (ZZ01_Gold-Franc)
    XFU("XFU"), // UIC-Franc (ZZ05_UIC-Franc)
    XOF("XOF"), // CFA Franc BCEAO (BENIN, BURKINA FASO, CÔTE D'IVOIRE, GUINEA-BISSAU, MALI, NIGER, SENEGAL, TOGO)
    XPD("XPD"), // Palladium (ZZ09_Palladium)
    XPF("XPF"), // CFP Franc (FRENCH POLYNESIA, NEW CALEDONIA, WALLIS AND FUTUNA)
    XPT("XPT"), // Platinum (ZZ10_Platinum)
    XRE("XRE"), // RINET Funds Code (ZZ02_RINET Funds Code)
    XSU("XSU"), // Sucre (SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE")
    XTS("XTS"), // Codes specifically reserved for testing purposes (ZZ06_Testing_Code)
    XUA("XUA"), // ADB Unit of Account (MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP)
    YDD("YDD"), // Yemeni Dinar (YEMEN)
    YER("YER"), // Yemeni Rial (YEMEN)
    YUD("YUD"), // New Yugoslavian Dinar (YUGOSLAVIA)
    YUM("YUM"), // New Dinar (YUGOSLAVIA)
    YUN("YUN"), // Yugoslavian Dinar (YUGOSLAVIA)
    ZAL("ZAL"), // Financial Rand (SOUTH AFRICA, LESOTHO)
    ZAR("ZAR"), // Rand (SOUTH AFRICA, LESOTHO, NAMIBIA)
    ZMK("ZMK"), // Zambian Kwacha (ZAMBIA)
    ZMW("ZMW"), // Zambian Kwacha (ZAMBIA)
    ZRN("ZRN"), // New Zaire (ZAIRE)
    ZRZ("ZRZ"), // Zaire (ZAIRE)
    ZWC("ZWC"), // Rhodesian Dollar (ZIMBABWE)
    ZWD("ZWD"), // Zimbabwe Dollar (ZIMBABWE)
    ZWL("ZWL"), // Zimbabwe Dollar (ZIMBABWE)
    ZWN("ZWN"), // Zimbabwe Dollar (new) (ZIMBABWE)
    ZWR("ZWR"); // Zimbabwe Dollar (ZIMBABWE)

    private final String code;

    /**
     * @param code currnecy code by ISO-4217
     */
    CurrencyCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
